# Generated by Django 2.2.5 on 2019-10-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_task_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='task',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
