# Generated by Django 2.2.5 on 2019-09-30 01:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoItem',
            new_name='Task',
        ),
    ]
